2013/05/28 06:06:17 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test.tbl_migration' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_migration`.
2013/05/28 06:20:46 [error] [system.db.CDbCommand] CDbCommand::execute() falló: SQLSTATE[HY000]: General error: 1005 Can't create table 'test.#sql-61a_10c' (errno: 150). La sentencia SQL ejecutada fue: ALTER TABLE `tbl_tarea` ADD CONSTRAINT `fk_tarea_usuario_propietario` FOREIGN KEY (`propietario_id`) REFERENCES `tbl_usuario` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT.
2013/05/28 06:20:46 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand falló al ejecutar la sentencia SQL: SQLSTATE[HY000]: General error: 1005 Can't create table 'test.#sql-61a_10c' (errno: 150). The SQL statement executed was: ALTER TABLE `tbl_tarea` ADD CONSTRAINT `fk_tarea_usuario_propietario` FOREIGN KEY (`propietario_id`) REFERENCES `tbl_usuario` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT' in /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/db/CDbCommand.php:357
Stack trace:
#0 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/db/CDbCommand.php(1432): CDbCommand->execute()
#1 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/db/CDbMigration.php(343): CDbCommand->addForeignKey('fk_tarea_usuari...', 'tbl_tarea', 'propietario_id', 'tbl_usuario', 'id', 'CASCADE', 'RESTRICT')
#2 /home/berni/projects/webapp/protected/migrations/m130525_162713_create_tarea_asignacion_table.php(32): CDbMigration->addForeignKey('fk_tarea_usuari...', 'tbl_tarea', 'propietario_id', 'tbl_usuario', 'id', 'CASCADE', 'RESTRICT')
#3 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/cli/commands/MigrateCommand.php(385): m130525_162713_create_tarea_asignacion_table->up()
#4 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/cli/commands/MigrateCommand.php(109): MigrateCommand->migrateUp('m130525_162713_...')
#5 [internal function]: MigrateCommand->actionUp(Array)
#6 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(MigrateCommand), Array)
#7 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/console/CConsoleCommandRunner.php(67): CConsoleCommand->run(Array)
#8 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/console/CConsoleApplication.php(91): CConsoleCommandRunner->run(Array)
#9 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/base/CApplication.php(169): CConsoleApplication->processRequest()
#10 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/yiic.php(33): CApplication->run()
#11 /home/berni/projects/webapp/protected/yiic.php(7): require_once('/opt/lampp/htdo...')
#12 /home/berni/projects/webapp/protected/yiic(4): require_once('/home/berni/pro...')
#13 {main}
---
2013/05/28 06:23:07 [error] [system.db.CDbCommand] CDbCommand::execute() falló: SQLSTATE[HY000]: General error: 1005 Can't create table 'test.#sql-61a_10d' (errno: 150). La sentencia SQL ejecutada fue: ALTER TABLE `tbl_tarea` ADD CONSTRAINT `fk_tarea_incidencia` FOREIGN KEY (`incidencia_id`) REFERENCES `tbl_incidencia` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT.
2013/05/28 06:23:07 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand falló al ejecutar la sentencia SQL: SQLSTATE[HY000]: General error: 1005 Can't create table 'test.#sql-61a_10d' (errno: 150). The SQL statement executed was: ALTER TABLE `tbl_tarea` ADD CONSTRAINT `fk_tarea_incidencia` FOREIGN KEY (`incidencia_id`) REFERENCES `tbl_incidencia` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT' in /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/db/CDbCommand.php:357
Stack trace:
#0 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/db/CDbCommand.php(1432): CDbCommand->execute()
#1 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/db/CDbMigration.php(343): CDbCommand->addForeignKey('fk_tarea_incide...', 'tbl_tarea', 'incidencia_id', 'tbl_incidencia', 'id', 'CASCADE', 'RESTRICT')
#2 /home/berni/projects/webapp/protected/migrations/m130525_162713_create_tarea_asignacion_table.php(30): CDbMigration->addForeignKey('fk_tarea_incide...', 'tbl_tarea', 'incidencia_id', 'tbl_incidencia', 'id', 'CASCADE', 'RESTRICT')
#3 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/cli/commands/MigrateCommand.php(385): m130525_162713_create_tarea_asignacion_table->up()
#4 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/cli/commands/MigrateCommand.php(109): MigrateCommand->migrateUp('m130525_162713_...')
#5 [internal function]: MigrateCommand->actionUp(Array)
#6 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(MigrateCommand), Array)
#7 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/console/CConsoleCommandRunner.php(67): CConsoleCommand->run(Array)
#8 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/console/CConsoleApplication.php(91): CConsoleCommandRunner->run(Array)
#9 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/base/CApplication.php(169): CConsoleApplication->processRequest()
#10 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/yiic.php(33): CApplication->run()
#11 /home/berni/projects/webapp/protected/yiic.php(7): require_once('/opt/lampp/htdo...')
#12 /home/berni/projects/webapp/protected/yiic(4): require_once('/home/berni/pro...')
#13 {main}
---
2013/05/28 06:24:03 [error] [system.db.CDbCommand] CDbCommand::execute() falló: SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'tbl_incidencia'. La sentencia SQL ejecutada fue: DROP TABLE `tbl_incidencia`.
2013/05/28 06:24:03 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand falló al ejecutar la sentencia SQL: SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'tbl_incidencia'. The SQL statement executed was: DROP TABLE `tbl_incidencia`' in /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/db/CDbCommand.php:357
Stack trace:
#0 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/db/CDbCommand.php(1344): CDbCommand->execute()
#1 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/db/CDbMigration.php(253): CDbCommand->dropTable('tbl_incidencia')
#2 /home/berni/projects/webapp/protected/migrations/m130525_162030_create_incidencia_table.php(22): CDbMigration->dropTable('tbl_incidencia')
#3 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/cli/commands/MigrateCommand.php(410): m130525_162030_create_incidencia_table->down()
#4 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/cli/commands/MigrateCommand.php(145): MigrateCommand->migrateDown('m130525_162030_...')
#5 [internal function]: MigrateCommand->actionDown(Array)
#6 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(MigrateCommand), Array)
#7 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/console/CConsoleCommandRunner.php(67): CConsoleCommand->run(Array)
#8 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/console/CConsoleApplication.php(91): CConsoleCommandRunner->run(Array)
#9 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/base/CApplication.php(169): CConsoleApplication->processRequest()
#10 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/yiic.php(33): CApplication->run()
#11 /home/berni/projects/webapp/protected/yiic.php(7): require_once('/opt/lampp/htdo...')
#12 /home/berni/projects/webapp/protected/yiic(4): require_once('/home/berni/pro...')
#13 {main}
---
2013/05/28 06:24:19 [error] [system.db.CDbCommand] CDbCommand::execute() falló: SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'tbl_incidencia'. La sentencia SQL ejecutada fue: DROP TABLE `tbl_incidencia`.
2013/05/28 06:24:19 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand falló al ejecutar la sentencia SQL: SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'tbl_incidencia'. The SQL statement executed was: DROP TABLE `tbl_incidencia`' in /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/db/CDbCommand.php:357
Stack trace:
#0 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/db/CDbCommand.php(1344): CDbCommand->execute()
#1 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/db/CDbMigration.php(253): CDbCommand->dropTable('tbl_incidencia')
#2 /home/berni/projects/webapp/protected/migrations/m130525_162030_create_incidencia_table.php(22): CDbMigration->dropTable('tbl_incidencia')
#3 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/cli/commands/MigrateCommand.php(410): m130525_162030_create_incidencia_table->down()
#4 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/cli/commands/MigrateCommand.php(145): MigrateCommand->migrateDown('m130525_162030_...')
#5 [internal function]: MigrateCommand->actionDown(Array)
#6 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(MigrateCommand), Array)
#7 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/console/CConsoleCommandRunner.php(67): CConsoleCommand->run(Array)
#8 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/console/CConsoleApplication.php(91): CConsoleCommandRunner->run(Array)
#9 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/base/CApplication.php(169): CConsoleApplication->processRequest()
#10 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/yiic.php(33): CApplication->run()
#11 /home/berni/projects/webapp/protected/yiic.php(7): require_once('/opt/lampp/htdo...')
#12 /home/berni/projects/webapp/protected/yiic(4): require_once('/home/berni/pro...')
#13 {main}
---
2013/05/28 06:25:05 [error] [system.db.CDbCommand] CDbCommand::execute() falló: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'tbl_tarea' already exists. La sentencia SQL ejecutada fue: CREATE TABLE `tbl_tarea` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`nombre` varchar(255) NOT NULL,
	`descripcion` text,
	`incidencia_id` int(11) DEFAULT NULL,
	`tipo_id` int(11) DEFAULT NULL,
	`estado_id` int(11) DEFAULT NULL,
	`propietario_id` int(11) DEFAULT NULL,
	`responsable_id` int(11) DEFAULT NULL,
	`create_time` datetime DEFAULT NULL,
	`create_user_id` int(11) DEFAULT NULL,
	`update_time` datetime DEFAULT NULL,
	`update_user_id` int(11) DEFAULT NULL
) ENGINE=InnoDB.
2013/05/28 06:25:05 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand falló al ejecutar la sentencia SQL: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'tbl_tarea' already exists. The SQL statement executed was: CREATE TABLE `tbl_tarea` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`nombre` varchar(255) NOT NULL,
	`descripcion` text,
	`incidencia_id` int(11) DEFAULT NULL,
	`tipo_id` int(11) DEFAULT NULL,
	`estado_id` int(11) DEFAULT NULL,
	`propietario_id` int(11) DEFAULT NULL,
	`responsable_id` int(11) DEFAULT NULL,
	`create_time` datetime DEFAULT NULL,
	`create_user_id` int(11) DEFAULT NULL,
	`update_time` datetime DEFAULT NULL,
	`update_user_id` int(11) DEFAULT NULL
) ENGINE=InnoDB' in /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/db/CDbCommand.php:357
Stack trace:
#0 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/db/CDbCommand.php(1321): CDbCommand->execute()
#1 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/db/CDbMigration.php(228): CDbCommand->createTable('tbl_tarea', Array, 'ENGINE=InnoDB')
#2 /home/berni/projects/webapp/protected/migrations/m130525_162713_create_tarea_asignacion_table.php(21): CDbMigration->createTable('tbl_tarea', Array, 'ENGINE=InnoDB')
#3 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/cli/commands/MigrateCommand.php(385): m130525_162713_create_tarea_asignacion_table->up()
#4 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/cli/commands/MigrateCommand.php(109): MigrateCommand->migrateUp('m130525_162713_...')
#5 [internal function]: MigrateCommand->actionUp(Array)
#6 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(MigrateCommand), Array)
#7 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/console/CConsoleCommandRunner.php(67): CConsoleCommand->run(Array)
#8 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/console/CConsoleApplication.php(91): CConsoleCommandRunner->run(Array)
#9 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/base/CApplication.php(169): CConsoleApplication->processRequest()
#10 /opt/lampp/htdocs/yii-1.1.13.e9e4a0/framework/yiic.php(33): CApplication->run()
#11 /home/berni/projects/webapp/protected/yiic.php(7): require_once('/opt/lampp/htdo...')
#12 /home/berni/projects/webapp/protected/yiic(4): require_once('/home/berni/pro...')
#13 {main}
---
2013/06/05 16:58:47 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'test_dbuser'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:381
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\web\auth\CDbAuthManager.php(589): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\web\auth\CDbAuthManager.php(59): CDbAuthManager->getDbConnection()
#5 C:\xampp\htdocs\yii\framework\base\CModule.php(387): CDbAuthManager->init()
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(185): CModule->getComponent('authManager')
#7 C:\xampp\htdocs\yii\framework\web\auth\CWebUser.php(806): CWebApplication->getAuthManager()
#8 C:\xampp\htdocs\webapp\protected\modules\rights\components\RWebUser.php(43): CWebUser->checkAccess('usuario', Array, true)
#9 C:\xampp\htdocs\webapp\themes\tpl_mantenimiento\views\layouts\main.php(76): RWebUser->checkAccess('usuario')
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#11 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div class="con...')
#14 C:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div class="con...')
#15 C:\xampp\htdocs\yii\framework\web\CBaseController.php(206): COutputProcessor->run()
#16 C:\xampp\htdocs\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#17 C:\xampp\htdocs\webapp\protected\views\layouts\column1.php(7): CBaseController->endContent()
#18 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#19 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#20 C:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#21 C:\xampp\htdocs\webapp\protected\controllers\SiteController.php(32): CController->render('index')
#22 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#23 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#24 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#25 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#26 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#27 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#28 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#29 C:\xampp\htdocs\webapp\index.php(15): CApplication->run()
#30 {main}
REQUEST_URI=/webapp/
---
2013/06/05 18:28:19 [error] [php] Object of class CInlineAction could not be converted to string (C:\xampp\htdocs\webapp\protected\views\incidencia\index.php:17)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): IncidenciaController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): IncidenciaController->renderPartial()
#2 C:\xampp\htdocs\webapp\protected\controllers\IncidenciaController.php(183): IncidenciaController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): IncidenciaController->actionMisincidencias()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): IncidenciaController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): IncidenciaController->filterAccessControl()
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): IncidenciaController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): IncidenciaController->run()
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\webapp\index.php(15): CWebApplication->run()
REQUEST_URI=/webapp/index.php/incidencia/misincidencias
2013/06/05 19:21:21 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tarea/view')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 C:\xampp\htdocs\webapp\index.php(15): CApplication->run()
#12 {main}
REQUEST_URI=/webapp/index.php/tarea/view?iid=6
HTTP_REFERER=http://localhost/webapp/index.php/tarea/5
---
2013/06/05 19:21:43 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('incidencia/view')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 C:\xampp\htdocs\webapp\index.php(15): CApplication->run()
#12 {main}
REQUEST_URI=/webapp/index.php/incidencia/view?iid=6
HTTP_REFERER=http://localhost/webapp/index.php/tarea/5
---
2013/06/05 19:23:46 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Su solicitud es inválida.' in C:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('incidencia/view')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 C:\xampp\htdocs\webapp\index.php(15): CApplication->run()
#12 {main}
REQUEST_URI=/webapp/index.php/incidencia/view?iid=6
HTTP_REFERER=http://localhost/webapp/index.php/tarea/6
---
